# Generated by Django 4.2 on 2023-04-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='CPF',
            field=models.CharField(db_index=True, max_length=11, unique=True),
        ),
    ]
