# Generated by Django 4.2 on 2023-04-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='CPF',
            field=models.CharField(db_index=True, max_length=14, unique=True),
        ),
    ]
